### PR TITLE
Updated elife/api-sdk to e9a8fdb: Fix profile identifier

### PR DESCRIPTION
**Pull request by elife-alfred-user**
I have run https://alfred.elifesciences.org/job/dependencies-search-update-api-sdk-php/32/display/redirect which resulted in this pull request.

### CODE REVIEW

**Comment by thewilkybarkid** [comment]
@giorgiosironi Updates required for Dockerised GoAws?

**Comment by giorgiosironi** [comment]
I think `goaws` is the hostname which is not visible outside of Docker containers, will link them up.

**Comment by giorgiosironi** [comment]
https://github.com/elifesciences/builder-base-formula/pull/117 should fix this.

**Comment by giorgiosironi** [comment]
It did (good prediction)

**Pull request merged**
