### PR TITLE
New Relic for long-running processes

### PR DESCRIPTION
**Pull request by giorgiosironi**
Pull request that depends on https://github.com/elifesciences/search/pull/73
Adds monitoring of every single Gearman task being executed, or element being accepted from SQS.
Renames the import command to `queue:import` as it does not have anything to do with Gearman anymore.

### CODE REVIEW

**Comment by stephenwf** [comment]
Had a look through, looks good. We have a centralised task runner, do you think it would be useful to have a custom metric set up in the "GearmanTaskDriver" for duration of running each task. Would give us some nice graphs on NR side

**Comment by stephenwf** [comment]
Possibly even hooking it up to Guzzle and having metrics for our external API calls for the long running processes too might be useful for debugging.

**Comment by giorgiosironi** [comment]
As far as I know the New Relic PHP extension measures external HTTP calls automatically (hooking in curl_*) and also measure time for single transactions (that's why we mark them with `newrelic_start_transaction()` and `newrelic_end_transaction()`)

**Comment by stephenwf** [comment]
Ah good to know, I didn't realise that sort of thing was just bundled in

**Comment by giorgiosironi** [comment]
I'll merge but after #73, because it depends on it.

**Pull request merged**
