### PR TITLE
Instrumenting ci-import to improve logging of failures

### PR DESCRIPTION
**Pull request by giorgiosironi**
I have seen the import failing a few times in pull requests, but the only thing that we check is that the number of Gearman jobs goes to zero (no matter if they are discarded as failed). The goal is to make the build read if at least a Gearman job fails.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Interestingly, this build hung.

**Comment by giorgiosironi** [comment]
It hung because the worker crashed. Note for future self: it is ok for the worker to crash as it will be respawned in `end2end` and `prod`. When you have a generic, unknown exception it's safer to terminate the process than to try pushing on with errors that may have corrupted the state of the process like a dropped database connection. In `ci`, these generic errors should not happena anyway.

**Comment by giorgiosironi** [comment]
Still working on a good synchronization on processes to stop the import on errors, but for now we can say we get:
```
{"message":"Validation of the JSON data failed:\nitems[0].type: Does not have a value in the enumeration [\"podcast-episode\"]\nitems[0].number: The property number is required\nitems[0].image: The property image is required\nitems[0].sources: The property sources is required\nitems[0].published: Does not match the regex pattern ^....-..-..T..:..:..Z$\nitems[0]: Failed to match all schemas\nitems[0].type: Does not have a value in the enumeration [\"collection\"]\nitems[0].updated: The property updated is required\nitems[0].selectedCurator: The property selectedCurator is required\nitems[0].type: Does not have a value in the enumeration [\"event\"]\nitems[0].starts: The property starts is required\nitems[0].ends: The property ends is required\nitems[0].type: Does not have a value in the enumeration [\"interview\"]\nitems[0].interviewee: The property interviewee is required\nitems[0].type: Does not have a value in the enumeration [\"labs-experiment\"]\nitems[0]: Failed to match exactly one schema\nitems[0].status: The property status is required\nitems[0].version: The property version is required\nitems[0].doi: The property doi is required\nitems[0].authorLine: The property authorLine is required\nitems[0].stage: The property stage is required\nitems[0].volume: The property volume is required\nitems[0].elocationId: The property elocationId is required\nitems[0].type: Does not have a value in the enumeration [\"correction\",\"editorial\",\"feature\",\"insight\",\"research-advance\",\"research-article\",\"research-exchange\",\"retraction\",\"registered-report\",\"replication-study\",\"short-report\",\"tools-resources\"]","context":[],"level":550,"level_name":"ALERT","channel":"search-api","datetime":{"date":"2017-01-05 11:14:17.814355","timezone_type":3,"timezone":"UTC"},"extra":{"process_id":6661}}
{"message":"Validation of the JSON data failed:\nitems[0].type: Does not have a value in the enumeration [\"podcast-episode\"]\nitems[0].sources: The property sources is required\nitems[0].published: Does not match the regex pattern ^....-..-..T..:..:..Z$\nitems[0]: Failed to match all schemas\nitems[0].type: Does not have a value in the enumeration [\"blog-article\"]\nitems[0].id: The property id is required\nitems[0].type: Does not have a value in the enumeration [\"collection\"]\nitems[0].updated: The property updated is required\nitems[0].selectedCurator: The property selectedCurator is required\nitems[0].type: Does not have a value in the enumeration [\"event\"]\nitems[0].starts: The property starts is required\nitems[0].ends: The property ends is required\nitems[0].type: Does not have a value in the enumeration [\"interview\"]\nitems[0].interviewee: The property interviewee is required\nitems[0]: Failed to match exactly one schema\nitems[0].status: The property status is required\nitems[0].version: The property version is required\nitems[0].doi: The property doi is required\nitems[0].authorLine: The property authorLine is required\nitems[0].stage: The property stage is required\nitems[0].volume: The property volume is required\nitems[0].elocationId: The property elocationId is required\nitems[0].type: Does not have a value in the enumeration [\"correction\",\"editorial\",\"feature\",\"insight\",\"research-advance\",\"research-article\",\"research-exchange\",\"retraction\",\"registered-report\",\"replication-study\",\"short-report\",\"tools-resources\"]","context":[],"level":550,"level_name":"ALERT","channel":"search-api","datetime":{"date":"2017-01-05 11:14:17.849942","timezone_type":3,"timezone":"UTC"},"extra":{"process_id":6661}}
```
I'll try to add also the stack trace to this.

**Comment by giorgiosironi** [comment]
Ok, now the SQS and Gearman queues have to be empty to decide the import is finished. At the moment they are not, so the build reliably fails. Debugging this after lunch to find out what are the main problems when importing the api-dummy data.

**Comment by giorgiosironi** [comment]
Found:
https://github.com/elifesciences/search/blob/3f7319d25ae0317c3e95cf2e9cd89c5d5a733511/src/Search/Queue/BasicTransformer.php#L62

**Comment by giorgiosironi** [comment]
I will update to the latest api-sdk-php because it has better error messages, but not sure it is related to the problems.

**Comment by stephenwf** [comment]
Maybe a rebase would work for the article error?

**Comment by giorgiosironi** [comment]
I will rebase to be up-to-date with the already solved problems.

**Comment by giorgiosironi** [comment]
Isolating to a single item, `/events/1`, this is the error in validating the translated `SearchResult` (composed by a single `EventResponse`):
```
elife@ci--search:/srv/search$ tail -n 1 var/logs/error.log | jq "." | grep error | sed -e 's/\\n/\r\n/g'
    "validation_error": "Validation of the JSON data failed:
items[0].type: Does not have a value in the enumeration [\"podcast-episode\"]
items[0].number: The property number is required
items[0].published: The property published is required
items[0].image: The property image is required
items[0].sources: The property sources is required
items[0]: Failed to match all schemas
items[0].type: Does not have a value in the enumeration [\"blog-article\"]
items[0].type: Does not have a value in the enumeration [\"collection\"]
items[0].updated: The property updated is required
items[0].selectedCurator: The property selectedCurator is required
items[0].starts: Does not match the regex pattern ^....-..-..T..:..:..Z$
items[0].ends: Does not match the regex pattern ^....-..-..T..:..:..Z$
items[0].type: Does not have a value in the enumeration [\"interview\"]
items[0].interviewee: The property interviewee is required
items[0].type: Does not have a value in the enumeration [\"labs-experiment\"]
items[0]: Failed to match exactly one schema
items[0].status: The property status is required
items[0].version: The property version is required
items[0].doi: The property doi is required
items[0].authorLine: The property authorLine is required
items[0].stage: The property stage is required
items[0].volume: The property volume is required
items[0].elocationId: The property elocationId is required
items[0].type: Does not have a value in the enumeration [\"correction\",\"editorial\",\"feature\",\"insight\",\"research-advance\",\"research-article\",\"research-exchange\",\"retraction\",\"registered-report\",\"replication-study\",\"short-report\",\"tools-resources\"]",
```

**Comment by giorgiosironi** [comment]
Yes, responses are serialized as:
```
{"total":1,"items":[{"starts":"2016-04-22T20:00:00+00:00","ends":"2016-04-22T20:00:00+00:00","timezone":"America\/Los_Angeles","type":"event","id":"1","title":"Changing peer review in cancer research: a seminar at Fred Hutch","impactStatement":"How eLife is influencing the culture of peer review"}],"types":{"correction":0,"editorial":0,"feature":0,"insight":0,"research-advance":0,"research-article":0,"research-exchange":0,"retraction":0,"registered-report":0,"replication-study":0,"short-report":0,"tools-resources":0,"blog-article":0,"collection":0,"event":0,"interview":0,"labs-experiment":0,"podcast-episode":0},"subjects":[{"id":"biophysics-structural-biology","name":"Biophysics Structural Biology","results":1}]}
```
Don't know where the date format is specified.

**Comment by stephenwf** [comment]
So the class that changes how that works is:
`eLife\Search\Api\Response\EventResponse` (lines 16 & 24)

From what I can see the Z should be preserved. Its maybe possible that the cache has not been cleared since it was updated. We could try running `bin/console cache:clear` as part of the build for CI (Although I thought we might already do that)?

**Comment by giorgiosironi** [comment]
We should already be doing that:
https://github.com/elifesciences/search-formula/blob/master/salt/search/init.sls#L87

**Comment by giorgiosironi** [comment]
Corrected the `cache:clear` command, it's improving now as I can see there is data in the index.

**Comment by giorgiosironi** [comment]
Looks like the remaining error is Collection `tropical-disease`.

**Comment by giorgiosironi** [comment]
Yes, now I am logging correctly the serialization of the search result:
```
 "search_result": "{\"updated\":\"2015-09-16T11:19:26Z\",\"selectedCurator\":{\"id\":\"pjha\",\"type\":\"senior-editor\",\"name\":{\"preferred\":\"Prabhat Jha\",\"index\":\"Jha, Prabhat\"},\"image\":{},\"etAl\":true}, ...
```

**Comment by giorgiosironi** [comment]
Now correctly fails again as there are 25 imported items while there should be 26 including the `Collection` that is failing due to the missing `selectedCurator.image`

**Comment by stephenwf** [comment]
@giorgiosironi Is the curator image a required field? Or is it because its an empty object? We can possibly change this in JMS:
http://jmsyst.com/libs/serializer/master/reference/annotations#accesstype

And having some sort of check so that if its not a valid image with no fields then it will simply return `null` which will get stripped out of the response.

**Comment by giorgiosironi** [comment]
It is because it's present but empty:
https://github.com/elifesciences/api-raml/blob/develop/src/snippets/person.v1.yaml#L18
https://github.com/elifesciences/api-raml/blob/develop/src/misc/image-thumbnail.v1.yaml#L47
The original data is:
```
   ...
            "selectedCurator": {                                                                                                                                 [330/535]
                "id": "pjha",
                "type": "senior-editor",
                "name": {
                    "preferred": "Prabhat Jha",
                    "index": "Jha, Prabhat"
                },
                "image": {
                    "alt": "",
                    "sizes": {
                        "16:9": {
                            "250": "http://localhost:8080/images/people/pjha/jpg?width=250&height=141",
                            "500": "http://localhost:8080/images/people/pjha/jpg?width=500&height=281"
                        },
                        "1:1": {
                            "70": "http://localhost:8080/images/people/pjha/jpg?width=70&height=70",
                            "140": "http://localhost:8080/images/people/pjha/jpg?width=140&height=140"
                        }
                    }
                },
                "etAl": true
            }
    ...
```
but in the search result object `image` is `{}`.

**Comment by stephenwf** [comment]
Here is the diff

```diff
───────────────────────────────────────────────────────────────────────────────────────────────────────
 -- a/src/Search/Api/Response/Common/NamedResponse.php
 ++ b/src/Search/Api/Response/Common/NamedResponse.php
───────────────────────────────────────────────────────────────────────────────────────────────────────
@@ -7,7 +7,11 @@ use JMS\Serializer\Annotation\Type;

 abstract class NamedResponse
 {
-     use Image;
+     /**
+      * @Type(eLife\Search\Api\Response\ImageThumbnailResponse::class)
+      * @Since(version="1")
+      */
+     public $image;

     /**
      * @Type("string")
```

**Comment by stephenwf** [comment]
Did that work now for importing? I see the error on build looks like a DNS issue

**Comment by giorgiosironi** [comment]
Not sure, I'll run it manually

**Comment by giorgiosironi** [comment]
Some other validation error:
```
items[0].selectedCurator.image.sizes.16:9.250: Does not match the regex pattern ^https://\nitems[0].selectedCurator.image.sizes.16:9.500: Does not match the regex pattern ^https://\nitems[0].selectedCurator.image.sizes.1:1.70: Does not match the regex pattern ^https://\nitems[0].selectedCurator.image.sizes.1:1.140: Does not match the regex pattern ^https://\nitems[0].selectedCurator: Failed to match all schemas
```

**Comment by stephenwf** [comment]
Ah okay, so this is with the api dummy content. Its all http only, so I added in a converter but its not being run since we changed to just the thumbnail. Give me a second and Ill get back to you

**Comment by giorgiosironi** [comment]
They are in HTTP instead of HTTPS, I see some other code around that transformed them?
```
    "search_result": "{\"updated\":\"2015-09-16T11:19:26Z\",\"selectedCurator\":{\"image\":{\"alt\":\"\",\"sizes\":{\"16:9\":{\"250\":\"http:\\/\\/localhost:8080\\/images\\/people\\/pjha\\/jpg?width=250&height=141\",\"500\":\"http:\\/\\/localhost:8080\\/images\\/people\\/pjha\\/jpg?width=500&height=281\"},\"1:1\":{\"70\":\"http:\\/\\/localhost:8080\\/images\\/people\\/pjha\\/jpg?width=70&height=70\",\"140\":\"http:\\/\\/localhost:8080\\/images\\/people\\/pjha\\/jpg?width=140&height=140\"}}},\"id\":\"pjha\",\"type\":\"senior-editor\",\"name\":{\"preferred\":\"Prabhat Jha\",\"index\":\"Jha, Prabhat\"},\"etAl\":true}
```

**Comment by stephenwf** [comment]
```diff
diff --git a/src/Search/Api/Response/Common/NamedResponse.php b/src/Search/Api/Response/Common/NamedResponse.php
index 9ea6d30..90a008e 100644
--- a/src/Search/Api/Response/Common/NamedResponse.php
+++ b/src/Search/Api/Response/Common/NamedResponse.php
@@ -2,6 +2,7 @@

 namespace eLife\Search\Api\Response\Common;

+use JMS\Serializer\Annotation\Accessor;
 use JMS\Serializer\Annotation\Since;
 use JMS\Serializer\Annotation\Type;

@@ -10,9 +11,15 @@ abstract class NamedResponse
     /**
      * @Type(eLife\Search\Api\Response\ImageThumbnailResponse::class)
      * @Since(version="1")
+     * @Accessor(getter="getHttpsImage")
      */
     public $image;

+    public function getHttpsImage()
+    {
+        return $this->image ? $this->image->https() : null;
+    }
+
     /**
      * @Type("string")
      * @Since(version="1")
```

**Comment by giorgiosironi** [comment]
I see 28 results in the index with a manual curl performed after the build has run, but during the ci-import the script says 27.

**Comment by giorgiosironi** [comment]
Now that part passes, I smell some cache/process not restarted problem.

**Comment by giorgiosironi** [comment]
Some minor fixed, but now passes reliably, merging.

**Pull request merged**
