### PR TITLE
ELPP-2296 Added use-date parameter

### PR DESCRIPTION
**Pull request by stephenwf**
@thewilkybarkid 

Sorry laptop about to die, no tests and no updates to published fields yet. I will add these when I'm back on Tuesday.

### CODE REVIEW

**Comment by stephenwf** [comment]
Managed to get the test and field update in... we will see if the test passes though!

**Comment by thewilkybarkid** [comment]
Looks like it covers the date range too, should have a test for that.

**Comment by stephenwf** [comment]
@thewilkybarkid I've added a test for sort now

**Comment by stephenwf** [comment]
Trying to fix the CS manually, having issues with my PHP 7 install (deleted homebrew)

**Comment by thewilkybarkid** [comment]
`elife/api-sdk` needs to be updated. I can push if you like.

**Comment by stephenwf** [comment]
that would be useful, thanks

**Comment by stephenwf** [comment]
Few failed tests, Ill get them sorted, thanks for updating though

**Comment by thewilkybarkid** [comment]
Green, but there's a few `Undefined index` notices.

**Comment by stephenwf** [comment]
Can't see the notices locally (`php -d error_reporting=32759 ./vendor/bin/phpunit`)

**Comment by stephenwf** [comment]
Oh I see yes thats from the mocked AWS queue from the Bus sdk ping @giorgiosironi not sure if its  major issue though

```
12:06:13 [52.204.5.217] out: Notice: Undefined index: ApproximateNumberOfMessagesDelayed in /srv/search/vendor/elife/bus-sdk/src/Queue/SqsWatchableQueue.php on line 105
```

So we can maybe just add a `?? 0` to the end of it to do an isset check
```
       $total = 0;
        foreach ($attributes as $attributeName) {
            $total += $result['Attributes'][$attributeName];
        }
```

**Pull request merged**
