### PR TITLE
gearman:worker should not hang on work()

### PR DESCRIPTION
**Pull request by giorgiosironi**
Like for queue:watch, it should wait for a finite amount and then loop to check for signals or other limits. The default behavior seem to be an infinite timeout.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Going with this otherwise all builds fail, but feel free to add comments.

**Comment by stephenwf** [comment]
The limits are not errors, but they are the cause of stopping the execution

**Comment by giorgiosironi** [comment]
Point was: when you log in into a server and check what's wrong in the `error.log`, you want to see things that have gone wrong, but a deployment would put the restart of the processes in there even if it's expected

**Comment by stephenwf** [comment]
That makes sense

**Pull request merged**
