### PR TITLE
Added search boosting/weightings

### PR DESCRIPTION
**Pull request by elrossco22**
@stephenwf

### CODE REVIEW

**Comment by giorgiosironi** [comment]
The original build didn't run because of an infrastructure problem, now fixed. Today's build needs coding style fixed before running the tests.

**Comment by stephenwf** [comment]
Hi @elrossco22 

This is just needing some tests covering whats added:
https://github.com/elifesciences/search/blob/develop/tests/src/Search/Web/SortOrderTest.php

Here is a similar test, you'll just need to create fixtures appropriately. 

It will probably need to be rebased too, but it looks like this will be isolated so no issue. Let me know if there are any issues with the web test case base class.

**Comment by giorgiosironi** [comment]
A rebase or merge is needed to solve conflicts, while `php-cs-fixer` can update the source files to conform to the coding standards (was the cause of the last build failure).

**Comment by stephenwf** [comment]
@elrossco22 I think the failure is coming from updating the API-SDK, there must be a regressions during import. Could you investigate or roll back the composer.json change?

**Comment by stephenwf** [comment]
@giorgiosironi Some Fabric exception, I'm not sure why its stopping the rest of the items entering the queue

```
 !!! Parallel execution exception under host u'52.72.82.210':
```

**Comment by giorgiosironi** [comment]
The api-dummy has changed recently to produce IIIF images, but search has been updated too so the api-sdk of `develop` should be good to go.

Taking a look inside the ci instance to see what's happening.

**Comment by giorgiosironi** [comment]
The assertion that is causing the failure is
```
15:25:47 [52.72.82.210] out: Total results in the index: 10
15:25:47 [52.72.82.210] out: There should be at least 22 results in the index
```
(all the rest of the output is just this error bubbling up)

**Comment by giorgiosironi** [comment]
It looks like a race condition, the waiting conditions gives up too early. Currently stressing it to see if it fails again.

**Comment by giorgiosironi** [comment]
Nope, when rerunning the build 10 results (instead of 22) remain indefinitely in the index.

**Comment by giorgiosironi** [comment]
e.g.
```
{
  "podcast-episode": 0,
  "retraction": 0,
  "research-exchange": 0,
  "research-article": 6,
  "research-advance": 1,
  "insight": 1,
  "feature": 1,
  "editorial": 1,
  "correction": 0,
  "registered-report": 0,
  "replication-study": 0,
  "short-report": 0,
  "tools-resources": 0,
  "blog-article": 0,
  "collection": 0,
  "interview": 0,
  "labs-experiment": 0
}
```
Trying to trace a blog article to see where it vanishes.

**Comment by elrossco22** [comment]
@giorgiosironi if there were types not in the above list that would explain the shortage

**Comment by giorgiosironi** [comment]
Take for example one the 3 blog articles, the logs say:
```
"Item (blog-article, 359325) being enqueued"
"Item (blog-article, 359325) enqueued successfully"
"queue:watch Running gearman task"
"queue:watch Committed task"
"BlogArticle<359325> validated against current schema."
"BlogArticle<359325> Indexing Media coverage: Slime can see"
"BlogArticle<359325> importing into Elasticsearch."
"Request Body"
"Request Success:"
"Request Success:"
"Response"
"BlogArticle<359325> successfully imported."
"Request Body"
```
but when selecting, a more specific query gives more results than a generic one:
```
elife@ci--search:~$ curl localhost/search | jq '.types["blog-article"]'                                                                                                   
0
elife@ci--search:~$ curl localhost/search?for=Slime | jq '.types["blog-article"]'
100  3123    0  3123    0     0   103k      0 --:--:-- --:--:-- --:--:--  105k
1
```
Is it expected? How can we write a query that counts all available results?

**Pull request merged**
