### PR TITLE
Updating api-sdk to newest version, without caching

### PR DESCRIPTION
**Pull request by giorgiosironi**

### CODE REVIEW

**Comment by stephenwf** [comment]
Looks good, do we have any metrics to compare against to show how this will affect memory during importing or queue watching?

**Comment by giorgiosironi** [comment]
Memory usage: https://rpm.newrelic.com/accounts/1451451/servers/26879341
Speed: https://ci--alfred.elifesciences.org/job/test-search/ (building times in ci/end2end, small dataset)

**Comment by stephenwf** [comment]
End to end times have jumped significantly!

**Comment by giorgiosironi** [comment]
Eheh no that's https://github.com/elifesciences/search/commit/b86e0555823286a95b948272fde306c31f424360
Previously search was running just a couple of end2end tests, but now it's been uniformed to the other projects in running all of them.

**Pull request merged**
