### PR TITLE
composer.json, allow the mindplay/composer-locator plugin.

### PR DESCRIPTION
**Pull request by lsh-0**
prevents composer from prompting for this and hanging highstate.
could have sworn I fixed this already ...

### CODE REVIEW

**Comment by lsh-0** [comment]
@nlisgo , could you take a look at this for me please?

```
elife@ci--search:/srv/search$ ./project_tests.sh 
............................................................ 60 / 99 (61%)
.......................................                      99 / 99 (100%)


Time: 751ms; Memory: 10MB

Warning: require_once(/srv/search/tests/../vendor/elife/api-sdk/test/TestCase.php): failed to open stream: No such file or directory in /srv/search/tests/bootstrap on line 11
Fatal error: require_once(): Failed opening required '/srv/search/tests/../vendor/elife/api-sdk/test/TestCase.php' (include_path='.:/usr/share/php') in /srv/search/tests/bootstrap on line 11
```

The root `./test` directory in `api-sdk` isn't present, just `./src`.

**Comment by nlisgo** [comment]
I can take a look.

**Comment by nlisgo** [comment]
To demonstrate that this issue is not related to this PR I have re-run a PR that previously ran with any error: https://alfred.elifesciences.org/blue/organizations/jenkins/pull-requests-projects%2Fsearch/detail/PR-381/2/pipeline

This time we get the same error. As long as `project_tests.sh` is run after `composer install` then the dependencies should be pulled in.

**Comment by lsh-0** [comment]
> To demonstrate that this issue is not related to this PR

yes, I know that, the problem I'm trying to solve is composer prompting to install mindplay/composer, however this error pops up. If you could keep digging I'd be grateful.

**Comment by nlisgo** [comment]
> yes, I know that

The failed pipeline I linked to in my comment was for a different PR that is currently open and the PR previously passed. See run 1: https://alfred.elifesciences.org/blue/organizations/jenkins/pull-requests-projects%2Fsearch/detail/PR-381/1/pipeline

I thought it was valuable to demonstrate that this error is now occurring indiscriminately.

There is nothing in that PR that introduces `mindplay/composer-locator`.

I believe it is related to composer 2. When we run `composer install` in ci I believe the full command now is `composer --ignore-platform-req=php --no-interaction install --classmap-authoritative` it is only bringing in the `src` folder and `LICENSE` file for some of our dependencies but there is nothing in the `composer.json` for the `api-sdk-php` repo to exclude other code.

More digging needed.

@scottaubrey any thoughts?

**Comment by scottaubrey** [comment]
@lsh-0 @nlisgo It looks to me like it's an issue with github (of all things!).

If you pull down https://api.github.com/repos/elifesciences/api-sdk-php/zipball/2430f058628313e994bc250d74aaa1a2b9f63853 (which is what my composer is pulling), or just visit the repo page for api-sdk-php and download the zip for master, you'll have a zip file without the tests folder. 

Fix that, and I reckon it'll work. Not sure what's caused that though.

**Comment by lsh-0** [comment]
> Edit: I found that culprit, probably: https://github.com/elifesciences/api-sdk-php/blob/master/.gitattributes

removing it here:
https://github.com/elifesciences/api-sdk-php/pull/227

**Comment by lsh-0** [comment]
ok, tests are green and I'm going to merge it in.

@nlisgo , you should be aware that the dependencies have been relocked to update php-api-sdk and 'something' has changed enough to cause the 'Too many open files' error. I've modified the project tests script to give the open files limit a bump from 1024 to 2048 and then reset it afterwards, but this is a hack - something is keeping a handle on too many files and it needs proper investigation.

**Pull request merged**
