### PR TITLE
Fixed the article type

### PR DESCRIPTION
**Pull request by stephenwf**

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Following up:
```
{"message":"-> Running gearman task","context":{"gearmanTask":"research_article_validate","type":"article","id":"10627"},"level":200,"level_name":"INFO","channel":"search
-api","datetime":{"date":"2016-12-19 13:58:00.716059","timezone_type":3,"timezone":"UTC"},"extra":{"process_id":19805}}
{"message":"GearmanTaskDriver task started","context":{"task":"research_article_validate"},"level":100,"level_name":"DEBUG","channel":"search-api","datetime":{"date":"201
6-12-19 13:58:00.716476","timezone_type":3,"timezone":"UTC"},"extra":{"process_id":19801}}
{"message":"ResearchArticle<10627> Validating The many mysteries of <i>Homo naledi</i>","context":[],"level":100,"level_name":"DEBUG","channel":"search-api","datetime":{"
date":"2016-12-19 13:58:00.723272","timezone_type":3,"timezone":"UTC"},"extra":{"process_id":19801}}
{"message":"Validation of the JSON data failed:\nitems[0].type: Does not have a value in the enumeration [\"podcast-episode\"]\nitems[0].number: The property number is re
quired\nitems[0].image: The property image is required\nitems[0].sources: The property sources is required\nitems[0].published: Does not match the regex pattern ^....-..-
..T..:..:..Z$\nitems[0]: Failed to match all schemas\nitems[0].type: Does not have a value in the enumeration [\"blog-article\"]\nitems[0].type: Does not have a value in 
the enumeration [\"collection\"]\nitems[0].updated: The property updated is required\nitems[0].selectedCurator: The property selectedCurator is required\nitems[0].type: D
oes not have a value in the enumeration [\"event\"]\nitems[0].starts: The property starts is required\nitems[0].ends: The property ends is required\nitems[0].type: Does n
ot have a value in the enumeration [\"interview\"]\nitems[0].interviewee: The property interviewee is required\nitems[0].type: Does not have a value in the enumeration [\
"labs-experiment\"]\nitems[0]: Failed to match exactly one schema\nitems[0].stage: The property stage is required\nitems[0].statusDate: Does not match the regex pattern ^
....-..-..T..:..:..Z$\nitems[0].status: Does not have a value in the enumeration [\"poa\"]","context":[],"level":550,"level_name":"ALERT","channel":"search-api","datetime
":{"date":"2016-12-19 13:58:00.756970","timezone_type":3,"timezone":"UTC"},"extra":{"process_id":19801}}
{"message":"Recoverable error...","context":{"exception":{"class":"eLife\\Search\\Gearman\\InvalidWorkflow","message":"ResearchArticle<10627> Invalid item tried to be imp
orted.","code":0,"file":"/srv/search/src/Search/Workflow/ResearchArticleWorkflow.php:68"}},"level":300,"level_name":"WARNING","channel":"search-api","datetime":{"date":"2
016-12-19 13:58:00.757735","timezone_type":3,"timezone":"UTC"},"extra":{"process_id":19801}}
```
This should be valid as far as I know, strange

**Comment by giorgiosironi** [comment]
I'd check also the level of these entries, most be should be `ERROR`

**Comment by stephenwf** [comment]
The datetime: 2016-12-19 13:58:00.723272

I think that might be being caught as invalid

**Comment by giorgiosironi** [comment]
That looks like a Monolog metadata; I'll try to decipher the errors and check that the article is seen as valid on the Lax side.

**Pull request merged**
