### PR TITLE
Importing in bulk by adding elements to consume to the queue

### PR DESCRIPTION
**Pull request by giorgiosironi**

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Green but not really:
```
16:05:20 [54.166.202.120] out:           ID: search-import-content
16:05:20 [54.166.202.120] out:     Function: cmd.run
16:05:20 [54.166.202.120] out:         Name: ./bin/ci-import ci
16:05:20 [54.166.202.120] out:       Result: True
16:05:20 [54.166.202.120] out:      Comment: Command "./bin/ci-import ci" run
16:05:20 [54.166.202.120] out:      Started: 16:04:10.801833
16:05:20 [54.166.202.120] out:     Duration: 60524.951 ms
16:05:20 [54.166.202.120] out:      Changes:   
16:05:20 [54.166.202.120] out:               ----------
16:05:20 [54.166.202.120] out:               pid:
16:05:20 [54.166.202.120] out:                   2216
16:05:20 [54.166.202.120] out:               retcode:
16:05:20 [54.166.202.120] out:                   0
16:05:20 [54.166.202.120] out:               stderr:
16:05:20 [54.166.202.120] out:                   
16:05:20 [54.166.202.120] out:                    1/3 [=========>------------------]  33%
16:05:20 [54.166.202.120] out:                    2/3 [==================>---------]  66%
16:05:20 [54.166.202.120] out:                    3/3 [============================] 100%Notice: Undefined offset: 3 in /srv/search/vendor/elife/api-sdk/src/SlicedIterator.php on line 16
16:05:20 [54.166.202.120] out:                   
16:05:20 [54.166.202.120] out:                    1/3 [=========>------------------]  33%
16:05:20 [54.166.202.120] out:                    2/3 [==================>---------]  66%
16:05:20 [54.166.202.120] out:                    3/3 [============================] 100%Notice: Undefined offset: 3 in /srv/search/vendor/elife/api-sdk/src/SlicedIterator.php on line 16
16:05:20 [54.166.202.120] out:                   
16:05:20 [54.166.202.120] out:                    1/2 [==============>-------------]  50%
16:05:20 [54.166.202.120] out:                    2/2 [============================] 100%Notice: Undefined offset: 2 in /srv/search/vendor/elife/api-sdk/src/SlicedIterator.php on line 16
16:05:20 [54.166.202.120] out:                   
16:05:20 [54.166.202.120] out:                    1/5 [=====>----------------------]  20%
16:05:20 [54.166.202.120] out:                    2/5 [===========>----------------]  40%
16:05:20 [54.166.202.120] out:                    3/5 [================>-----------]  60%
16:05:20 [54.166.202.120] out:                    4/5 [======================>-----]  80%
16:05:20 [54.166.202.120] out:                    5/5 [============================] 100%Notice: Undefined offset: 5 in /srv/search/vendor/elife/api-sdk/src/SlicedIterator.php on line 16
16:05:20 [54.166.202.120] out:                   
16:05:20 [54.166.202.120] out:                    1/4 [=======>--------------------]  25%
16:05:20 [54.166.202.120] out:                    2/4 [==============>-------------]  50%
16:05:20 [54.166.202.120] out:                    3/4 [=====================>------]  75%
16:05:20 [54.166.202.120] out:                    4/4 [============================] 100%Notice: Undefined offset: 4 in /srv/search/vendor/elife/api-sdk/src/SlicedIterator.php on line 16
16:05:20 [54.166.202.120] out:                   
16:05:20 [54.166.202.120] out:                    1/1 [============================] 100%Notice: Undefined offset: 1 in /srv/search/vendor/elife/api-sdk/src/SlicedIterator.php on line 16
16:05:20 [54.166.202.120] out:                   
16:05:20 [54.166.202.120] out:                     1/10 [==>-------------------------]  10%
16:05:20 [54.166.202.120] out:                     2/10 [=====>----------------------]  20%
16:05:20 [54.166.202.120] out:                     3/10 [========>-------------------]  30%
16:05:20 [54.166.202.120] out:                     4/10 [===========>----------------]  40%
16:05:20 [54.166.202.120] out:                     5/10 [==============>-------------]  50%
16:05:20 [54.166.202.120] out:                     6/10 [================>-----------]  60%
16:05:20 [54.166.202.120] out:                     7/10 [===================>--------]  70%
16:05:20 [54.166.202.120] out:                     8/10 [======================>-----]  80%
16:05:20 [54.166.202.120] out:                     9/10 [=========================>--]  90%
16:05:20 [54.166.202.120] out:                    10/10 [============================] 100%Notice: Undefined offset: 10 in /srv/search/vendor/elife/api-sdk/src/SlicedIterator.php on line 16
16:05:20 [54.166.202.120] out:                   Notice: Undefined index: published in /srv/search/vendor/elife/api-sdk/src/Serializer/BlogArticleNormalizer.php on line 68
16:05:20 [54.166.202.120] out:                   ./bin/ci-import: line 17: kill: (2217) - No such process
16:05:20 [54.166.202.120] out:               stdout:
16:05:20 [54.166.202.120] out:                   [2016-12-20 16:04:10] search-api.ERROR: There was an unknown problem importing research-article (04395) {"exception":"[object] (LogicException(code: 0): ApiSDK does not exist for the type `research-article`. at /srv/search/src/Search/Queue/BasicTransformer.php:48)","item":"[object] (eLife\\Search\\Queue\\InternalSqsMessage: {})"} 
16:05:20 [54.166.202.120] out:                   [2016-12-20 16:04:11] search-api.ALERT: Validation of the JSON data failed: items[0].type: Does not have a value in the enumeration ["podcast-episode"] items[0].number: The property number is required items[0].image: The property image is required items[0].sources: The property sources is required items[0].published: Does not match the regex pattern ^....-..-..T..:..:..Z$ items[0]: Failed to match all schemas items[0].type: Does not have a value in the enumeration ["collection"] items[0].updated: The property updated is required items[0].selectedCurator: The property selectedCurator is required items[0].type: Does not have a value in the enumeration ["event"] items[0].starts: The property starts is required items[0].ends: The property ends is required items[0].type: Does not have a value in the enumeration ["interview"] items[0].interviewee: The property interviewee is required items[0].type: Does not have a value in the enumeration ["labs-experiment"] items[0]: Failed to match exactly one schema items[0].status: The property status is required items[0].version: The property version is required items[0].doi: The property doi is required items[0].authorLine: The property authorLine is required items[0].stage: The property stage is required items[0].volume: The property volume is required items[0].elocationId: The property elocationId is required items[0].type: Does not have a value in the enumeration ["correction","editorial","feature","insight","research-advance","research-article","research-exchange","retraction","registered-report","replication-study","short-report","tools-resources"]  
16:05:20 [54.166.202.120] out:                   [2016-12-20 16:04:11] search-api.WARNING: Recoverable error... {"exception":"[object] (eLife\\Search\\Gearman\\InvalidWorkflow(code: 0): BlogArticle<339482> Invalid item tried to be imported. at /srv/search/src/Search/Workflow/BlogArticleWorkflow.php:57)"} 
16:05:20 [54.166.202.120] out:                   [2016-12-20 16:04:11] search-api.ALERT: PodcastEpisode<3> Invalid item trid to be imported. {"type":"podcast-episode","number":3} 
16:05:20 [54.166.202.120] out:                   [2016-12-20 16:04:11] search-api.WARNING: Recoverable error... {"exception":"[object] (eLife\\Search\\Gearman\\InvalidWorkflow(code: 0): PodcastEpisode<3> Invalid item tried to be imported. at /srv/search/src/Search/Workflow/PodcastEpisodeWorkflow.php:59)"} 
16:05:20 [54.166.202.120] out:                   [2016-12-20 16:04:11] search-api.ALERT: Validation of the JSON data failed: items[0].type: Does not have a value in the enumeration ["podcast-episode"] items[0].sources: The property sources is required items[0].published: Does not match the regex pattern ^....-..-..T..:..:..Z$ items[0]: Failed to match all schemas items[0].type: Does not have a value in the enumeration ["blog-article"] items[0].id: The property id is required items[0].type: Does not have a value in the enumeration ["collection"] items[0].updated: The property updated is required items[0].selectedCurator: The property selectedCurator is required items[0].type: Does not have a value in the enumeration ["event"] items[0].starts: The property starts is required items[0].ends: The property ends is required items[0].type: Does not have a value in the enumeration ["interview"] items[0].interviewee: The property interviewee is required items[0]: Failed to match exactly one schema items[0].status: The property status is required items[0].version: The property version is required items[0].doi: The property doi is required items[0].authorLine: The property authorLine is required items[0].stage: The property stage is required items[0].volume: The property volume is required items[0].elocationId: The property elocationId is required items[0].type: Does not have a value in the enumeration ["correction","editorial","feature","insight","research-advance","research-article","research-exchange","retraction","registered-report","replication-study","short-report","tools-resources"]  
16:05:20 [54.166.202.120] out:                   [2016-12-20 16:04:11] search-api.WARNING: Recoverable error... {"exception":"[object] (eLife\\Search\\Gearman\\InvalidWorkflow(code: 0): LabsExperiment<1> Invalid item tried to be imported. at /srv/search/src/Search/Workflow/LabsExperimentWorkflow.php:56)"} 
16:05:20 [54.166.202.120] out:                   [2016-12-20 16:04:11] search-api.ALERT: PodcastEpisode<1> Invalid item trid to be imported. {"type":"podcast-episode","number":1} 
16:05:20 [54.166.202.120] out:                   [2016-12-20 16:04:11] search-api.WARNING: Recoverable error... {"exception":"[object] (eLife\\Search\\Gearman\\InvalidWorkflow(code: 0): PodcastEpisode<1> Invalid item tried to be imported. at /srv/search/src/Search/Workflow/PodcastEpisodeWorkflow.php:59)"} 
16:05:20 [54.166.202.120] out:                   [2016-12-20 16:04:11] search-api.ERROR: There was an unknown problem importing research-article (13410) {"exception":"[object] (LogicException(code: 0): ApiSDK does not exist for the type `research-article`. at /srv/search/src/Search/Queue/BasicTransformer.php:48)","item":"[object] (eLife\\Search\\Queue\\InternalSqsMessage: {})"} 
16:05:20 [54.166.202.120] out:                   [2016-12-20 16:04:11] search-api.ALERT: PodcastEpisode<1> Invalid item trid to be imported. {"type":"podcast-episode","number":1} 
16:05:20 [54.166.202.120] out:                   [2016-12-20 16:04:11] search-api.WARNING: Recoverable error... {"exception":"[object] (eLife\\Search\\Gearman\\InvalidWorkflow(code: 0): PodcastEpisode<1> Invalid item tried to be imported. at /srv/search/src/Search/Workflow/PodcastEpisodeWorkflow.php:59)"} 
16:05:20 [54.166.202.120] out:                   [2016-12-20 16:04:11] search-api.ERROR: There was an unknown problem importing research-article (16412) {"exception":"[object] (LogicException(code: 0): ApiSDK does not exist for the type `research-article`. at /srv/search/src/Search/Queue/BasicTransformer.php:48)","item":"[object] (eLife\\Search\\Queue\\InternalSqsMessage: {})"} 
16:05:20 [54.166.202.120] out:                   [2016-12-20 16:04:11] search-api.ALERT: Validation of the JSON data failed: items[0].type: Does not have a value in the enumeration ["podcast-episode"] items[0].number: The property number is required items[0].image: The property image is required items[0].sources: The property sources is required items[0].published: Does not match the regex pattern ^....-..-..T..:..:..Z$ items[0]: Failed to match all schemas items[0].type: Does not have a value in the enumeration ["collection"] items[0].updated: The property updated is required items[0].selectedCurator: The property selectedCurator is required items[0].type: Does not have a value in the enumeration ["event"] items[0].starts: The property starts is required items[0].ends: The property ends is required items[0].type: Does not have a value in the enumeration ["interview"] items[0].interviewee: The property interviewee is required items[0].type: Does not have a value in the enumeration ["labs-experiment"] items[0]: Failed to match exactly one schema items[0].status: The property status is required items[0].version: The property version is required items[0].doi: The property doi is required items[0].authorLine: The property authorLine is required items[0].stage: The property stage is required items[0].volume: The property volume is required items[0].elocationId: The property elocationId is required items[0].type: Does not have a value in the enumeration ["correction","editorial","feature","insight","research-advance","research-article","research-exchange","retraction","registered-report","replication-study","short-report","tools-resources"]  
16:05:20 [54.166.202.120] out:                   [2016-12-20 16:04:11] search-api.WARNING: Recoverable error... {"exception":"[object] (eLife\\Search\\Gearman\\InvalidWorkflow(code: 0): BlogArticle<345983> Invalid item tried to be imported. at /srv/search/src/Search/Workflow/BlogArticleWorkflow.php:57)"} 
16:05:20 [54.166.202.120] out:                   [2016-12-20 16:04:11] search-api.ALERT: Validation of the JSON data failed: items[0].type: Does not have a value in the enumeration ["podcast-episode"] items[0].number: The property number is required items[0].image: The property image is required items[0].sources: The property sources is required items[0].published: Does not match the regex pattern ^....-..-..T..:..:..Z$ items[0]: Failed to match all schemas items[0].type: Does not have a value in the enumeration ["collection"] items[0].updated: The property updated is required items[0].selectedCurator: The property selectedCurator is required items[0].type: Does not have a value in the enumeration ["event"] items[0].starts: The property starts is required items[0].ends: The property ends is required items[0].type: Does not have a value in the enumeration ["interview"] items[0].interviewee: The property interviewee is required items[0].type: Does not have a value in the enumeration ["labs-experiment"] items[0]: Failed to match exactly one schema items[0].status: The property status is required items[0].version: The property version is required items[0].doi: The property doi is required items[0].authorLine: The property authorLine is required items[0].stage: The property stage is required items[0].volume: The property volume is required items[0].elocationId: The property elocationId is required items[0].type: Does not have a value in the enumeration ["correction","editorial","feature","insight","research-advance","research-article","research-exchange","retraction","registered-report","replication-study","short-report","tools-resources"]  
16:05:20 [54.166.202.120] out:                   [2016-12-20 16:04:11] search-api.WARNING: Recoverable error... {"exception":"[object] (eLife\\Search\\Gearman\\InvalidWorkflow(code: 0): BlogArticle<339482> Invalid item tried to be imported. at /srv/search/src/Search/Workflow/BlogArticleWorkflow.php:57)"} 
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   [2016-12-20 16:04:11] search-api.ERROR: There was an unknown problem importing research-article (16846) {"exception":"[object] (LogicException(code: 0): ApiSDK does not exist for the type `research-article`. at /srv/search/src/Search/Queue/BasicTransformer.php:48)","item":"[object] (eLife\\Search\\Queue\\InternalSqsMessage: {})"} 
16:05:20 [54.166.202.120] out:                   [2016-12-20 16:04:11] search-api.ERROR: There was an unknown problem importing research-article (16412) {"exception":"[object] (LogicException(code: 0): ApiSDK does not exist for the type `research-article`. at /srv/search/src/Search/Queue/BasicTransformer.php:48)","item":"[object] (eLife\\Search\\Queue\\InternalSqsMessage: {})"} 
16:05:20 [54.166.202.120] out:                   [2016-12-20 16:04:11] search-api.ALERT: PodcastEpisode<2> Invalid item trid to be imported. {"type":"podcast-episode","number":2} 
16:05:20 [54.166.202.120] out:                   [2016-12-20 16:04:11] search-api.WARNING: Recoverable error... {"exception":"[object] (eLife\\Search\\Gearman\\InvalidWorkflow(code: 0): PodcastEpisode<2> Invalid item tried to be imported. at /srv/search/src/Search/Workflow/PodcastEpisodeWorkflow.php:59)"} 
16:05:20 [54.166.202.120] out:                   [2016-12-20 16:04:11] search-api.CRITICAL: Argument 3 passed to eLife\ApiSdk\Model\BlogArticle::__construct() must be an instance of DateTimeImmutable, boolean given, called in /srv/search/vendor/elife/api-sdk/src/Serializer/BlogArticleNormalizer.php on line 71  
16:05:20 [54.166.202.120] out:                   [2016-12-20 16:04:11] search-api.ERROR: There was an unknown problem importing research-article (16846) {"exception":"[object] (LogicException(code: 0): ApiSDK does not exist for the type `research-article`. at /srv/search/src/Search/Queue/BasicTransformer.php:48)","item":"[object] (eLife\\Search\\Queue\\InternalSqsMessage: {})"} 
16:05:20 [54.166.202.120] out:                   [2016-12-20 16:04:11] search-api.ERROR: There was an unknown problem importing research-article (16412) {"exception":"[object] (LogicException(code: 0): ApiSDK does not exist for the type `research-article`. at /srv/search/src/Search/Queue/BasicTransformer.php:48)","item":"[object] (eLife\\Search\\Queue\\InternalSqsMessage: {})"} 
16:05:20 [54.166.202.120] out:                   [2016-12-20 16:04:11] search-api.ERROR: There was an unknown problem importing research-article (09560) {"exception":"[object] (LogicException(code: 0): ApiSDK does not exist for the type `research-article`. at /srv/search/src/Search/Queue/BasicTransformer.php:48)","item":"[object] (eLife\\Search\\Queue\\InternalSqsMessage: {})"} 
16:05:20 [54.166.202.120] out:                   [2016-12-20 16:04:11] search-api.ERROR: There was an unknown problem importing research-article (13410) {"exception":"[object] (LogicException(code: 0): ApiSDK does not exist for the type `research-article`. at /srv/search/src/Search/Queue/BasicTransformer.php:48)","item":"[object] (eLife\\Search\\Queue\\InternalSqsMessage: {})"} 
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out:                   Job in queue: 1
16:05:20 [54.166.202.120] out: ----------
```

**Comment by stephenwf** [comment]
So we are pushing to the SQS every type/id, then it gets caught and processed in the normal queue watching command which already has the memory optimisations etc. That makes sense.

I suppose too its not actually increasing requests to APIs, only moving the `get(id)` requests somewhere else.

👍

**Comment by giorgiosironi** [comment]
Yes, it's moving the `GET /articles/:id` (and similar requests) from the main process to the gearman:worker and queue:watch. Now I am trying to correctly set up `bin/ci-import` so that it detects whether there are any errors and it cleans the SQS queue before starting.

**Comment by giorgiosironi** [comment]
Not satisfied with the errors not detected in `ci-import`, but stable enough on articles to bring it in production.

**Pull request merged**
