### PR TITLE
Updated SDK for figures wrapping

### PR DESCRIPTION
**Pull request by giorgiosironi**

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Some problems in importing collections, did something change in that schema in the last weeks?

**Comment by thewilkybarkid** [comment]
It'll be https://github.com/elifesciences/api-raml/pull/164.

**Comment by giorgiosironi** [comment]
Trying to replicate the build errors locally, I get
```
Doctrine\Common\Annotations\AnnotationException: [Semantical Error] The annotation "@JMS\Serializer\Annotation\Type" in property eLife\Search\Api\Response\CollectionRespo
nse::$updated does not exist, or could not be auto-loaded.
```

**Comment by giorgiosironi** [comment]
Tests were not runnable in isolation locally, getting closer but the Web tests still fail.

**Comment by giorgiosironi** [comment]
The error message locally was an HTML default error page, I want the same as `ci` where it tells you the actual problem with a JSON response.

**Pull request merged**
