### PR TITLE
Added test covering information from ELPP-1929

### PR DESCRIPTION
**Pull request by stephenwf**
@giorgiosironi Covers the case you mentioned in 1929 (I cannot replicate)

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Maybe there is a problem in the SDK?

**Comment by giorgiosironi** [comment]
Yes, found it.

**Comment by giorgiosironi** [comment]
https://github.com/elifesciences/api-sdk-php/pull/99

**Comment by giorgiosironi** [comment]
Would close this as the problem isn't here?

**Comment by giorgiosironi** [comment]
Or maybe substitute with upgrade of api-sdk when fixed.

**Comment by stephenwf** [comment]
I will wait until there is an update to `api-sdk`, this was meant to replicate the issue to try and track it down.

**Comment by giorgiosironi** [comment]
Ok, but this test does not replicate it (probably it skips that part of the sdk in its data import phase) so a different test would be needed.

**Comment by giorgiosironi** [comment]
Closing in favor of #102

**Pull request closed without merging**
