### PR TITLE
Fixed build index flag

### PR DESCRIPTION
**Pull request by stephenwf**
@giorgiosironi

### CODE REVIEW

**Comment by giorgiosironi** [comment]
:+1: for the change, but wait to rebase on merged #83 as the current worker may cause some problems with the build

**Comment by stephenwf** [comment]
No problem, just seen this, maybe we should catch this and just sleep():

screen shot 2017-01-10 at 11 32 36

**Comment by giorgiosironi** [comment]
Seen it too, to start from an empty slate the build purges the queue making it contain nothing before starting to import items. Apparently AWS rate limits this, so we can't start a build more often than 1 per minute.

**Comment by giorgiosironi** [comment]
Rebase now to make it green.

**Comment by giorgiosironi** [comment]
Very interesting
```
13:49:25 [54.172.95.158] out: Total results in the index: 23
13:49:25 [54.172.95.158] out: There should be at least 28 results in the index
```
do we have sufficient logs to find out where the remaining 5 are stuck?

**Comment by stephenwf** [comment]
```
{"message":"gearman:worker: Unrecoverable error, stopping","context":{"exception":{"class":"Elasticsearch\\Common\\Exceptions\\Conflict409Exception","message":"{\"_shards\":{\"total\":10,\"successful\":4,\"failed\":1},\"elife_search\":{\"total\":10,\"successful\":4,\"failed\":1,\"failures\":[{\"shard\":3,\"reason\":\"pending operations\",\"routing\":{\"state\":\"STARTED\",\"primary\":true,\"node\":\"g2pDehqjSYqTv6p-FpwyxA\",\"relocating_node\":null,\"shard\":3,\"index\":\"elife_search\",\"version\":2,\"allocation_id\":{\"id\":\"kaPW7wSmTaqmzmQDIP_QKg\"}}}]}}","code":409,"file":"/srv/search/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:574"}},"level":500,"level_name":"CRITICAL","channel":"search-api","datetime":{"date":"2017-01-10 14:08:45.377203","timezone_type":3,"timezone":"UTC"},"extra":{"process_id":13377}}
```

**Comment by stephenwf** [comment]
@giorgiosironi @elrossco22 Good to go if you could take a look

**Pull request merged**
