### PR TITLE
Upgrade api-sdk to get UnknownReference support

### PR DESCRIPTION
**Pull request by giorgiosironi**
Empirically this work to solve errors during `gearman:import all`. Let's see if the test suite is green.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Lots of `Error: Class 'eLife\ApiSdk\Serializer\Block\FileNormalizer' not found`, what else should we upgrade?

**Comment by stephenwf** [comment]
Ah this will probably need to be updated with the new normalizer:
https://github.com/elifesciences/search/blob/develop/tests/src/Search/Workflow/GetSerializer.php

**Comment by giorgiosironi** [comment]
That should be provided by the SDK right? Even if this is customized, I can add a method there to remove the duplication.

**Comment by stephenwf** [comment]
It's a bit of a pain, in the API SDK its in here: https://github.com/elifesciences/api-sdk-php/blob/master/src/ApiSdk.php

We could instantiate the class and try and pull the serializer out and set it on our object, I just didn't feel this was the cleanest solution.

**Comment by giorgiosironi** [comment]
Making a comparison of the two lists, I see that some Normalizers have changed location (`FileNormalizer` moved outside of `Block` and more are missing besides it, like the `UnknownReferenceNormalizer`. From `ApiSdk` it's not easy to extract the `Serializer` without being very invasive (extracting a trait), I'll try to pull it out from there with the goal of having it always working right after the `composer update` on `elife/api-sdk`.

**Comment by giorgiosironi** [comment]
Ok, works now.

**Comment by stephenwf** [comment]
Looks good, much cleaner 👍

**Pull request merged**
