### PR TITLE
Removed mocked data

### PR DESCRIPTION
**Pull request by stephenwf**
@elrossco22 @giorgiosironi 

This will be the last test for CI and end2end, it removes the safe-guard that made it pass last time. This will uncover the last of the issues.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
The smoke tests fail on `search--ci` when this PR is applied:
```
13:05:44 [54.208.157.163] out: ++ curl --write-out '%{http_code}' --silent --output /dev/null localhost/search
13:05:44 [54.208.157.163] out: + '[' 500 == 200 ']'
```
If you SSH into the machine you can take a look at why.

**Comment by stephenwf** [comment]
I checked the box and it looks like the dummy-api is not being pulled in, would this require the merging of the builder pull request?

**Comment by giorgiosironi** [comment]
Needs some update of builder-private, I'll do it and restart the build.

**Comment by stephenwf** [comment]
@giorgiosironi Looks like the elasticsearch index is not being created from this command: https://github.com/elifesciences/search-formula/blob/master/salt/search/init.sls#L52-L59

**Comment by giorgiosironi** [comment]
In the output at https://ci--alfred.elifesciences.org/job/pull-requests-projects/job/search/job/PR-42/4/console
```
14:45:50 [54.175.109.5] out:           ID: search-ensure-index
14:45:50 [54.175.109.5] out:     Function: cmd.run
14:45:50 [54.175.109.5] out:         Name: ./bin/console search:setup
14:45:50 [54.175.109.5] out:       Result: True
14:45:50 [54.175.109.5] out:      Comment: Command "./bin/console search:setup" run
14:45:50 [54.175.109.5] out:      Started: 14:45:43.961190
14:45:50 [54.175.109.5] out:     Duration: 53.273 ms
14:45:50 [54.175.109.5] out:      Changes:   
14:45:50 [54.175.109.5] out:               ----------
14:45:50 [54.175.109.5] out:               pid:
14:45:50 [54.175.109.5] out:                   3769
14:45:50 [54.175.109.5] out:               retcode:
14:45:50 [54.175.109.5] out:                   0
14:45:50 [54.175.109.5] out:               stderr:
14:45:50 [54.175.109.5] out:               stdout:
14:45:50 [54.175.109.5] out:                   Environment `local` not found.
```
Return code should be different from `0` to stop the build.

**Comment by stephenwf** [comment]
Good thing its an easy fix! Ill get on it

**Comment by stephenwf** [comment]
Looks like 8080 doesn't have the dummy:

```
15:33:55 [184.72.75.191] out:                     [eLife\ApiClient\Exception\NetworkProblem]                                   
15:33:55 [184.72.75.191] out:                     cURL error 7: Failed to connect to localhost port 8080: Connection refused   
15:33:55 [184.72.75.191] out:                     (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)                      
15:33:55 [184.72.75.191] out:                                                                                                  
15:33:55 [184.72.75.191] out:                   
15:33:55 [184.72.75.191] out:                                                                                                  
15:33:55 [184.72.75.191] out:                     [GuzzleHttp\Exception\ConnectException]                                      
15:33:55 [184.72.75.191] out:                     cURL error 7: Failed to connect to localhost port 8080: Connection refused   
15:33:55 [184.72.75.191] out:                     (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)                      
15:33:55 [184.72.75.191] out:                                                                                         
```

**Comment by stephenwf** [comment]
Wait, looks like another issue:

```log
15:33:54 [184.72.75.191] out: ----------
15:33:54 [184.72.75.191] out:           ID: api-dummy-repository
15:33:54 [184.72.75.191] out:     Function: builder.git_latest
15:33:54 [184.72.75.191] out:         Name: git@github.com:elifesciences/api-dummy.git
15:33:54 [184.72.75.191] out:       Result: False
15:33:54 [184.72.75.191] out:      Comment: Fetch did not successfully retrieve rev '7f1a36aaa10fd2fc13e974ad7795b5cbb5f2b55e' from git@github.com:elifesciences/api-dummy.git: Command 'git rev-parse 7f1a36aaa10fd2fc13e974ad7795b5cbb5f2b55e^{commit}' failed: fatal: ambiguous argument '7f1a36aaa10fd2fc13e974ad7795b5cbb5f2b55e^{commit}': unknown revision or path not in the working tree.
15:33:54 [184.72.75.191] out:               Use '--' to separate paths from revisions, like this:
15:33:54 [184.72.75.191] out:               'git <command> [<revision>...] -- [<file>...]'
15:33:54 [184.72.75.191] out:      Started: 15:33:45.198976
15:33:54 [184.72.75.191] out:     Duration: 676.295 ms
```

**Comment by stephenwf** [comment]
`'git rev-parse 7f1a36aaa10fd2fc13e974ad7795b5cbb5f2b55e^{commit}' failed: fatal: ambiguous argument '7f1a36aaa10fd2fc13e974ad7795b5cbb5f2b55e^{commit}'`

How can the full SHA be ambiguous 😆

**Comment by giorgiosironi** [comment]
The sha is the one of the `search` commit, but it's interfering with the `api-dummy` commit as it's global for the instance

**Comment by giorgiosironi** [comment]
This
https://github.com/elifesciences/api-dummy-formula/blob/master/salt/api-dummy/init.sls#L25
is referring to a value. We want that to be `master` here but stay that way when it is used as a standalone project, will need some convoluted expression there.

**Comment by giorgiosironi** [comment]
I'll add a pillar to api-dummy:
```
api_dummy: 
    standalone: True
```
and I will override this for `search` as:
```
api_dummy: 
    standalone: False
```
Write an if based on that in the api-dummy-formula to insert `rev: master` when this is `False`.

**Comment by giorgiosironi** [comment]
This one:
https://github.com/elifesciences/api-dummy-formula
Test the formula on your Vagrant VM, it should still work there first deploying the `master` of api-dummy. When it works there we can test it here.

**Comment by giorgiosironi** [comment]
`branch` should stay like that, it's just the name of the local branch.

**Comment by stephenwf** [comment]
@giorgiosironi Would you like me to make the changes?

**Comment by stephenwf** [comment]
Just tested locally, seems to be working

**Comment by stephenwf** [comment]
Of course it worked locally for me, the ref wasn't a SHA, it would have just been master which worked for both. I've updated the search formula: https://github.com/elifesciences/search-formula/pull/10

Is that the correct way to override?

**Comment by giorgiosironi** [comment]
Yes, but it's still missing changes to the api-dummy-formula to actually use that pillar.

**Comment by giorgiosironi** [comment]
api-dummy has been deployed correctly and is listening on 8080 now.

**Comment by giorgiosironi** [comment]
Annoying notice appearing often:
```
[16-Nov-2016 18:38:25 UTC] PHP Notice:  Undefined index: mock_queue in /srv/search/src/Search/Kernel.php on line 321
```

**Comment by giorgiosironi** [comment]
`/bin/console gearman:import all --env=ci` taking a while it seems, we'll look into optimizing it for faster builds maybe.

**Comment by stephenwf** [comment]
Ah theres no worker!

**Comment by giorgiosironi** [comment]
So it just went on for 11 hours before a Jenkins restart stopped it. I'll put an hard limit on build times of 1 hour to be safer.

In general long-running processes should not be running on `ci`, as they interfere with test suites. There is probably some script you can write that starts a worker, runs the import, terminates the worker?

**Comment by stephenwf** [comment]
@giorgiosironi Once this is merged: https://github.com/elifesciences/search-formula/pull/11 we can run the test again.

**Comment by stephenwf** [comment]
Pushing now!

**Comment by giorgiosironi** [comment]
Passing. One notice coming out:
```
09:58:19 [54.159.245.82] out:                    10/10 [============================] 100%Notice: Undefined property: stdClass::$body in /srv/search/src/Search/Workflow/ResearchArticleWorkflow.php on line 124
```
It took `16956.602 ms`, which means the `sleep 15` is a big part of it, is that really necessary?

**Comment by stephenwf** [comment]
Obviously we can tweak it, want me to drop it to 2 seconds?

**Comment by giorgiosironi** [comment]
Not sure what is the purpose, does the process get to the `sleep` call before the import is finished? If so we should have a more robust condition than sleeping (checking some state in the database), but I though at the moment `gearman:import all` was synchronous and wouldn't exit until it is finished (because we were using `doLow` and not `doLowBackground`.)

**Comment by stephenwf** [comment]
@giorgiosironi @elrossco22 @thewilkybarkid 

We are getting one validation issue with podcasts:

```
10:05:36 [54.159.245.82] out:                   ALERT: Validation of the JSON data failed:
10:05:36 [54.159.245.82] out:                   items[0].type: Does not have a value in the enumeration ["podcast-episode"]
10:05:36 [54.159.245.82] out:                   items[0].number: The property number is required
10:05:36 [54.159.245.82] out:                   items[0].published: The property published is required
10:05:36 [54.159.245.82] out:                   items[0].sources: The property sources is required
10:05:36 [54.159.245.82] out:                   items[0]: Failed to match all schemas
10:05:36 [54.159.245.82] out:                   items[0].type: Does not have a value in the enumeration ["blog-article"]
10:05:36 [54.159.245.82] out:                   items[0].selectedCurator.image.alt: The property alt is required
10:05:36 [54.159.245.82] out:                   items[0].selectedCurator.image.sizes: The property sizes is required
10:05:36 [54.159.245.82] out:                   items[0].selectedCurator: Failed to match all schemas
10:05:36 [54.159.245.82] out:                   items[0].type: Does not have a value in the enumeration ["event"]
10:05:36 [54.159.245.82] out:                   items[0].starts: The property starts is required
10:05:36 [54.159.245.82] out:                   items[0].ends: The property ends is required
10:05:36 [54.159.245.82] out:                   items[0].type: Does not have a value in the enumeration ["interview"]
10:05:36 [54.159.245.82] out:                   items[0].interviewee: The property interviewee is required
10:05:36 [54.159.245.82] out:                   items[0].type: Does not have a value in the enumeration ["labs-experiment"]
10:05:36 [54.159.245.82] out:                   items[0]: Failed to match exactly one schema
10:05:36 [54.159.245.82] out:                   items[0].status: The property status is required
10:05:36 [54.159.245.82] out:                   items[0].version: The property version is required
10:05:36 [54.159.245.82] out:                   items[0].doi: The property doi is required
10:05:36 [54.159.245.82] out:                   items[0].authorLine: The property authorLine is required
10:05:36 [54.159.245.82] out:                   items[0].statusDate: The property statusDate is required
10:05:36 [54.159.245.82] out:                   items[0].volume: The property volume is required
10:05:36 [54.159.245.82] out:                   items[0].elocationId: The property elocationId is required
10:05:36 [54.159.245.82] out:                   items[0].type: Does not have a value in the enumeration ["correction","editorial","feature","insight","research-advance","research-article","research-exchange","retraction","registered-report","replication-study","short-report","tools-resources"]
```

I think I'll need to update the API/API SDK soon to get it working with any changes to the Api dummy since its pulling from master branch of the dummy.


@giorgiosironi The gearman import is synchronous, but the worker that is picking up the jobs is not, so we run doLow for the first step and then the rest of the steps are ran asynchronously.

**Comment by giorgiosironi** [comment]
So the ending condition for the import script should be that we have requested some entities to be imported (do we have a counter?) and that they have appeared into the index. Or, there are no more Gearman jobs queued to be run, whatever is the easiest. Sleeping would mean that if there is an error in the asynchronous jobs we don't see it.

It may be simpler by the way to run this (which is starting to look like a functional test) as part of `project_tests.sh` rather than in the formula?

**Comment by stephenwf** [comment]
I think having it in salt allows the local dev environments to get set up and ready to go (with content), which is what we are looking for.

If there is an error in the gearman worker we will get the logs, the logs I posted above was from the worker, if for some reason the process is killed before its finished, the only outcome will be less data in the elasticsearch, which I don't think will affect things too much. The worker tasks are built in such a way that invalid information doesn't make it into elasticsearch at all, and this functionality is tested else where.

As far as seeing a status of an import, that would be quite a challenge. We have set up a logger for the CLI that we intended to change so that errors get logged to disk (or wherever). Then we can have a way to see which items did not get imported successfully. 

The challenge is the groups of tasks (e.g. from a gearman:import) are not grouped when they get the gearman, so tracing back to the original command is not currently possible, which makes reporting also impossible.

The first task that is synchronous is the validation, if this step fails we should be able to report if the validation failed, but the worker will report in the console anyway.

**Comment by giorgiosironi** [comment]
I installed the `gearadmin` command through the formula, so now you can do this command (which gives the number of jobs in the queue) instead of `sleep`:
```
elife@ci--search:~$ gearadmin --status | cut -f 2 | paste -sd+ | bc
5
elife@ci--search:~$ gearadmin --status | cut -f 2 | paste -sd+ | bc
2
elife@ci--search:~$ gearadmin --status | cut -f 2 | paste -sd+ | bc
0
```
Repeating it in a loop and exiting when the count is 0 will be a reliable way of declaring the import finished.

**Comment by stephenwf** [comment]
@giorgiosironi Any chance you could cancel the build?

**Comment by stephenwf** [comment]
I have a feeling that killing the previous background process `$!` wont work with the script now..

**Comment by stephenwf** [comment]
@giorgiosironi I'm not sure what went wrong!

**Comment by giorgiosironi** [comment]
Killed builds and restarted new ones, but #15 seems still hanging.

**Comment by giorgiosironi** [comment]
In order:

1. log in into the machine to kill the processes if a build hangs, you may not have permissions to kill the job on Alfred and it may leave the orphan PHP process there anyway interfering with new builds
1. add some log statements inside the loop to see what's happening, they will be useful any time this runs
1. the count is only done once, I think the condition becomes something like `"4" -eq "0"` and will never become true.

**Comment by stephenwf** [comment]
@giorgiosironi Okay I've simplified the loop, lets see if it still hangs

**Comment by stephenwf** [comment]
(That seemed to work!)

**Comment by stephenwf** [comment]
@giorgiosironi @elrossco22 Good to merge?

**Comment by giorgiosironi** [comment]
:+1: for merging

**Pull request merged**
