### PR TITLE
ELPP-2260 Removed events from search

### PR DESCRIPTION
**Pull request by stephenwf**
@giorgiosironi @thewilkybarkid

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Needs to rebuild the index in production right?

**Comment by giorgiosironi** [comment]
Also, the console or at least the `queue:watch` process seems to be crashing during the build.

**Comment by giorgiosironi** [comment]
I'd say embargo: do not merge this until this afternoon, has we have demos at 11am.

**Comment by stephenwf** [comment]
@giorgiosironi Would you like me to re-progress this this morning

**Comment by giorgiosironi** [comment]
Yes, no blocker.

**Comment by stephenwf** [comment]
@giorgiosironi should be good to go now 👍

**Pull request merged**
