### PR TITLE
ELPP-1763 Added ID argument to queue command

### PR DESCRIPTION
**Pull request by stephenwf**
Yes I spelt the branch wrong

@giorgiosironi @elrossco22

### CODE REVIEW

**Comment by giorgiosironi** [comment]
The formula uses this command, which does not start the command:
```
$ php bin/console queue:watch search--end2end -e end2end 1
                                                          
  [Symfony\Component\Console\Exception\RuntimeException]  
  Too many arguments, expected arguments "command" "id".  

queue:watch [-i|--interval [INTERVAL]] [-t|--timeout [TIMEOUT]] [-l|--iterations [ITERATIONS]] [-m|--memory [MEMORY]] [-M|--memory-interval [MEMORY-INTERVAL]] [-T|--queue-timeout [QUEUE-TIMEOUT]] [-k|--mock [MOCK]] [--] [<id>]
```
The `-e` is not in the list of options but it's some kind of Symfony Console magic accepting it. The other argument which is the name of the queue is not specified too.

**Comment by stephenwf** [comment]
Maybe swapping it around:
```
$ php bin/console queue:watch search--end2end {id} --env=end2end
```

**Comment by giorgiosironi** [comment]
```
$ php bin/console queue:watch search--end2end 1 --env=end2end                                                                            
                                                          
  [Symfony\Component\Console\Exception\RuntimeException]  
  Too many arguments, expected arguments "command" "id".                                                            

queue:watch [-i|--interval [INTERVAL]] [-t|--timeout [TIMEOUT]] [-l|--iterations [ITERATIONS]] [-m|--memory [MEMORY]] [-M|--memory-interval [MEMORY-INTERVAL]] [-T|--queue-timeout [QUEUE-TIMEOUT]] [-k|--mock [MOCK]] [--] [<id>]
```
I'm not sure where the first argument is defined as https://github.com/elifesciences/search/blob/develop/src/Search/Gearman/Command/QueueCommand.php#L54 only shows one `addArgument()`.

**Comment by giorgiosironi** [comment]
In fact this passes the Symfony Console validation but fails later:
```
$ php bin/console queue:watch 1 --env=end2end --verbose
Loop start... [
-> Listening to topic 

                                        
  [LogicException]                      
  ApiSDK does not exist for that type.  
                                        

Exception trace:
 () at /srv/search/src/Search/Queue/BasicTransformer.php:48
 eLife\Search\Queue\SqsMessageTransformer->getSdk() at /srv/search/src/Search/Queue/BasicTransformer.php:54
 eLife\Search\Queue\SqsMessageTransformer->transform() at /srv/search/src/Search/Gearman/Command/QueueCommand.php:137
 eLife\Search\Gearman\Command\QueueCommand->loop() at /srv/search/src/Search/Gearman/Command/QueueCommand.php:121
 eLife\Search\Gearman\Command\QueueCommand->execute() at /srv/search/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at /srv/search/vendor/symfony/console/Application.php:820
 Symfony\Component\Console\Application->doRunCommand() at /srv/search/vendor/symfony/console/Application.php:187
 Symfony\Component\Console\Application->doRun() at /srv/search/vendor/symfony/console/Application.php:118
 Symfony\Component\Console\Application->run() at /srv/search/src/Search/Console.php:330
 eLife\Search\Console->run() at /srv/search/bin/console:23

queue:watch [-i|--interval [INTERVAL]] [-t|--timeout [TIMEOUT]] [-l|--iterations [ITERATIONS]] [-m|--memory [MEMORY]] [-M|--memory-interval [MEMORY-INTERVAL]] [-T|--queue-timeout [QUEUE-TIMEOUT]] [-k|--mock [MOCK]] [--] [<id>]
```

**Comment by stephenwf** [comment]
Okay so that error happens when an item in Queue is not recognised by the application, I think we can definitely change this to not fail fatally

**Comment by giorgiosironi** [comment]
So the command line in the formula is wrong, I will correct it to avoid passing in the queue name argument.

**Comment by giorgiosironi** [comment]
https://github.com/elifesciences/search-formula/commit/a93bdf5a99cb10293f16d1523890e6d447d149ba

**Pull request merged**
