### PR TITLE
Added new stage field

### PR DESCRIPTION
**Pull request by stephenwf**
@giorgiosironi @thewilkybarkid

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Going through https://github.com/elifesciences/api-raml/commits/develop/src/snippets/article.v1.yaml there is also a `versionDate` being added.

**Comment by stephenwf** [comment]
I've added that field too, looks to be optional though. Also added in validation when we are running through our tests, this will catch these in future. I do remember it being in before, but it is now

**Comment by giorgiosironi** [comment]
Ok, I guess then updating the api-raml and running a build will catch similar errors?
Bringing this to production.

**Comment by stephenwf** [comment]
Yes thats right, it won't catch optional fields, but won't cause BC breaks

**Pull request merged**
